"""English words in the sound titles, in Japanese, for the app's search and
for each family's Japanese name. A word maps to what is shown, then (after
a space) readings and other words a child might type. Words not here are
left out of the Japanese name; the English one is always searchable too."""

WORDS = {
    # what makes the sound
    "abacus": "そろばん", "airplane": "飛行機 ひこうき", "aircraft": "飛行機 ひこうき", "plane": "飛行機 ひこうき",
    "airport": "空港 くうこう", "alarm": "アラーム", "alien": "宇宙人 うちゅうじん エイリアン", "ambience": "環境音 かんきょうおん",
    "animal": "動物 どうぶつ", "anvil": "金床 かなとこ", "apple": "りんご", "applause": "拍手 はくしゅ", "arcade": "アーケード ゲーム",
    "armor": "よろい", "arrow": "矢 や", "artifact": "神器 じんぎ", "baby": "赤ちゃん あかちゃん", "bag": "かばん ふくろ",
    "ball": "ボール", "banknote": "お札 おさつ", "banknotes": "お札 おさつ", "baseball": "野球 やきゅう", "basement": "地下室 ちかしつ",
    "bat": "コウモリ バット", "battery": "電池 でんち", "bead": "玉 たま", "bear": "クマ", "bed": "ベッド", "bee": "ハチ",
    "bell": "ベル 鐘 かね", "bicycle": "自転車 じてんしゃ", "bird": "鳥 とり", "birdsong": "鳥 とり さえずり", "blacksmith": "鍛冶屋 かじや",
    "blanket": "毛布 もうふ", "boat": "ボート 船 ふね", "body": "体 からだ", "bomb": "爆弾 ばくだん", "bone": "骨 ほね", "bonfire": "たき火 たきび",
    "book": "本 ほん", "boot": "ブーツ", "boots": "ブーツ", "bottle": "びん ボトル", "bow": "弓 ゆみ", "bowl": "おわん ボウル",
    "box": "箱 はこ", "boxing": "ボクシング", "branch": "枝 えだ", "breath": "息 いき", "breeze": "そよ風 かぜ", "brick": "レンガ",
    "bridge": "橋 はし", "brook": "小川 おがわ", "broom": "ほうき", "brush": "ブラシ ふで", "bubble": "あわ", "bubbles": "あわ",
    "bucket": "バケツ", "bullet": "弾 たま", "burner": "コンロ", "bus": "バス", "button": "ボタン", "buzzer": "ブザー",
    "cabin": "機内 きない", "calculator": "電卓 でんたく", "camera": "カメラ", "campfire": "キャンプファイヤー たき火",
    "candle": "ろうそく", "cannon": "大砲 たいほう", "canvas": "キャンバス 布 ぬの", "cap": "ふた キャップ", "car": "車 くるま",
    "card": "カード", "cardboard": "段ボール だんぼーる", "cards": "カード トランプ", "carpet": "じゅうたん", "carrot": "にんじん",
    "cart": "カート", "cash": "お金 おかね", "cat": "ネコ ねこ", "cave": "どうくつ", "chain": "くさり", "chair": "いす",
    "chest": "宝箱 たからばこ", "chicken": "ニワトリ", "church-style": "教会 きょうかい", "cicada": "セミ", "city": "街 まち",
    "clock": "時計 とけい", "cloth": "布 ぬの", "clothing": "服 ふく", "coin": "コイン お金 おかね", "coins": "コイン お金 おかね",
    "computer": "パソコン", "concrete": "コンクリート", "console": "ゲーム機", "conveyor": "ベルトコンベア", "cotton": "わた",
    "cow": "ウシ うし", "cowbell": "カウベル", "crate": "木箱 きばこ", "creature": "生き物 いきもの モンスター", "cricket": "コオロギ",
    "crossbow": "クロスボウ 弓 ゆみ", "crow": "カラス", "crowd": "人々 ひとびと 観客 かんきゃく", "cucumber": "きゅうり", "cup": "コップ カップ",
    "curtain": "カーテン", "cutlery": "ナイフ フォーク", "cymbal": "シンバル", "deck": "トランプ", "denim": "デニム", "desk": "つくえ",
    "device": "機械 きかい", "dice": "サイコロ", "die": "サイコロ", "dinosaur": "恐竜 きょうりゅう", "dirt": "土 つち", "dog": "イヌ いぬ",
    "dolphin-style": "イルカ", "door": "ドア とびら", "doorbell": "チャイム インターホン", "dragon": "ドラゴン", "drawer": "引き出し ひきだし",
    "dress": "ドレス", "drill": "ドリル", "drum": "太鼓 たいこ ドラム", "duck": "アヒル カモ", "duffel": "かばん", "ear": "耳 みみ",
    "earthquake": "地震 じしん", "elephant": "ゾウ ぞう", "elevator": "エレベーター", "embers": "火 ひ", "enemy": "敵 てき",
    "engine": "エンジン", "eye": "目 め", "fabric": "布 ぬの", "factory": "工場 こうじょう", "fan": "扇風機 せんぷうき", "film": "フィルム",
    "fire": "火 ひ ほのお", "fireball": "火の玉 ひのたま", "firecracker": "爆竹 ばくちく 花火", "firework": "花火 はなび",
    "fireplace": "だんろ", "flag": "旗 はた", "flame": "ほのお 火 ひ", "flashlight": "懐中電灯 かいちゅうでんとう", "flock": "群れ むれ",
    "floor": "ゆか", "floorboard": "ゆか", "fly": "ハエ", "food": "食べ物 たべもの", "footstep": "足音 あしおと", "footsteps": "足音 あしおと",
    "forest": "森 もり", "forge": "鍛冶場 かじば", "fountain": "噴水 ふんすい", "fox": "キツネ", "frog": "カエル", "gas": "ガス",
    "gears": "歯車 はぐるま", "gear": "歯車 はぐるま", "geta": "げた", "giraffe": "キリン", "glass": "ガラス コップ", "glockenspiel-style": "鉄琴 てっきん",
    "goat": "ヤギ", "golem": "ゴーレム", "gong": "ドラ", "goose": "ガチョウ", "gorilla": "ゴリラ", "grass": "草 くさ", "gravel": "じゃり",
    "gun": "銃 じゅう", "gunshot": "銃 じゅう", "hall": "ホール", "hallway": "ろうか", "hammer": "ハンマー かなづち", "hamster": "ハムスター",
    "hand": "手 て", "harp": "ハープ", "head": "頭 あたま", "heartbeat": "心臓 しんぞう ドキドキ", "heels": "ヒール くつ", "hen": "ニワトリ",
    "hi-hat": "ハイハット", "highway": "高速道路 こうそくどうろ", "hinges": "ちょうつがい", "horn": "ラッパ クラクション", "horse": "ウマ うま",
    "house": "家 いえ", "human": "人 ひと", "ice-like": "氷 こおり", "insect": "虫 むし", "instrument": "楽器 がっき", "interface": "ボタン 画面",
    "iron": "鉄 てつ", "jacket": "上着 うわぎ", "jet": "ジェット", "jets": "ジェット", "kalimba": "カリンバ", "key": "キー カギ",
    "keyboard": "キーボード", "keypad": "キーボード", "kids": "子ども こども", "kitchen": "台所 だいどころ キッチン", "kitten": "子ネコ こねこ",
    "knife": "ナイフ", "knight": "騎士 きし", "lamp": "ランプ 電気 でんき", "laptop": "パソコン", "laser": "レーザー ビーム",
    "launcher": "発射台 はっしゃだい", "leather": "革 かわ", "leaves": "葉っぱ はっぱ", "lever": "レバー", "lion": "ライオン",
    "lock": "カギ かぎ", "longbow": "弓 ゆみ", "machine": "機械 きかい", "machinery": "機械 きかい", "magazine": "雑誌 ざっし",
    "magnifier": "虫めがね むしめがね", "marble": "ビー玉 びーだま", "marimba-style": "マリンバ 木琴 もっきん", "market": "市場 いちば",
    "meat": "肉 にく", "medical": "病院 びょういん", "metal": "金属 きんぞく", "microphone": "マイク", "missile": "ミサイル",
    "monitor": "モニター", "monkey": "サル さる", "monster": "モンスター 怪物 かいぶつ", "mosquito": "カ 蚊", "motor": "モーター",
    "motorcycle": "バイク", "mountain": "山 やま", "mouse": "マウス ネズミ", "mouth": "口 くち", "mud": "どろ", "mug": "マグカップ",
    "ocean": "海 うみ", "office": "事務所 じむしょ", "owl": "フクロウ", "pan": "フライパン なべ", "paper": "紙 かみ", "papers": "紙 かみ",
    "park": "公園 こうえん", "pavement": "道 みち", "paw": "足 あし", "pea": "豆 まめ", "pen": "ペン", "pencil": "えんぴつ",
    "phone": "電話 でんわ", "piece": "コマ", "pig": "ブタ ぶた", "pine": "松 まつ", "plastic": "プラスチック", "plate": "お皿 おさら",
    "playground-style": "公園 こうえん", "plush": "ぬいぐるみ", "police": "パトカー 警察 けいさつ", "pond": "池 いけ", "portal": "ワープ ゲート",
    "portcullis": "門 もん", "potato": "じゃがいも", "powder": "粉 こな", "radio": "ラジオ", "rain": "雨 あめ", "receiver": "受話器 じゅわき",
    "record": "レコード", "refrigerator": "冷蔵庫 れいぞうこ", "register": "レジ", "restaurant": "レストラン", "revolver": "銃 じゅう",
    "rifle": "銃 じゅう", "road": "道路 どうろ", "robot": "ロボット", "rocket": "ロケット", "roof": "屋根 やね", "room": "部屋 へや",
    "rooster": "ニワトリ", "rope": "ロープ なわ", "rubber": "ゴム", "school": "学校 がっこう", "scissors": "ハサミ はさみ",
    "seagull": "カモメ", "seesaw": "シーソー", "sheep": "ヒツジ ひつじ", "sheet": "紙 かみ シーツ", "shield": "盾 たて バリア",
    "ship": "船 ふね 宇宙船", "shoe": "くつ", "shoes": "くつ", "shore": "浜辺 はまべ", "shotgun": "銃 じゅう", "shovel": "スコップ",
    "shuriken": "手裏剣 しゅりけん", "sidewalk": "歩道 ほどう", "silver": "銀 ぎん", "siren": "サイレン", "ski": "スキー", "slime": "スライム",
    "slot": "スロット", "snare": "スネア 太鼓 たいこ", "sneakers": "スニーカー くつ", "snow": "雪 ゆき", "soap": "せっけん", "soccer": "サッカー",
    "songbird": "小鳥 ことり", "spacecraft": "宇宙船 うちゅうせん", "sparrow": "スズメ", "spike": "トゲ", "stadium-sized": "スタジアム",
    "stairs": "階段 かいだん", "stamp": "スタンプ はんこ", "stapler": "ホチキス", "steam": "湯気 ゆげ", "steel": "鉄 てつ", "stone": "石 いし",
    "stones": "石 いし", "stopwatch": "ストップウォッチ", "stream": "小川 おがわ", "surf": "波 なみ", "sword": "剣 けん", "table": "テーブル つくえ",
    "tail": "しっぽ", "tape": "テープ", "telephone": "電話 でんわ", "terminal": "端末 たんまつ", "theater": "劇場 げきじょう", "thunder": "雷 かみなり",
    "tile": "タイル", "timer": "タイマー", "tire": "タイヤ", "tom": "太鼓 たいこ", "torch": "たいまつ", "towel": "タオル", "toy": "おもちゃ",
    "traffic": "車 くるま 交通 こうつう", "train": "電車 でんしゃ", "transformer": "変圧器 へんあつき", "treasure": "宝 たから", "tree": "木 き",
    "trombone-style": "トロンボーン", "trophy": "トロフィー", "trumpet": "トランペット", "tv": "テレビ", "twig": "小枝 こえだ", "twigs": "小枝 こえだ",
    "typewriter": "タイプライター", "vehicle": "乗り物 のりもの", "vibraphone-style": "鉄琴 てっきん", "video": "ビデオ", "vinyl": "レコード",
    "voice": "声 こえ", "wall": "かべ", "watermelon": "スイカ すいか", "water": "水 みず", "waterfall": "滝 たき", "waves": "波 なみ",
    "wheel": "車輪 しゃりん", "wheels": "車輪 しゃりん", "whistle": "笛 ふえ ホイッスル", "wind": "風 かぜ", "window": "窓 まど",
    "wine": "ワイン", "wings": "つばさ はね", "wingbeats": "はばたき", "wolf": "オオカミ", "wood": "木 き", "wooden": "木 き",
    "woodblock": "ウッドブロック 木 き", "workshop": "工房 こうぼう", "wristwatch": "腕時計 うでどけい", "zebra": "シマウマ",
    "zipper": "チャック ファスナー", "coin-dropped": "コイン",
    # what it does
    "achievement": "達成 たっせい", "activation": "起動 きどう", "alert": "お知らせ おしらせ アラート", "answer": "答え こたえ",
    "applaud": "拍手 はくしゅ", "attack": "攻撃 こうげき", "bark": "ほえる", "barking": "ほえる", "barks": "ほえる", "beep": "ピッ ビープ",
    "beeps": "ピッ ビープ", "beeping": "ピッ ビープ", "bite": "かむ", "blast": "爆発 ばくはつ", "blink": "まばたき", "blip": "ピコッ",
    "blow": "ふく", "boing": "ボヨーン ばね", "bonk": "ゴツン", "boom": "ドーン", "bounce": "はねる バウンド", "bouncing": "はねる バウンド",
    "braam": "ブォーン", "brake": "ブレーキ", "braking": "ブレーキ", "break": "こわれる", "breaking": "こわれる", "buzz": "ブー",
    "buzzing": "ブーン", "call": "鳴き声 なきごえ 呼び出し", "celebration": "お祝い おいわい", "charge": "チャージ ためる", "charging": "チャージ ためる",
    "cheer": "歓声 かんせい", "cheering": "歓声 かんせい", "checkpoint": "チェックポイント", "chime": "チャイム キラーン", "chimes": "チャイム",
    "chirp": "さえずり", "chirping": "さえずり", "chomp": "パクッ 食べる", "chewing": "かむ 食べる", "click": "クリック カチッ",
    "clicking": "カチカチ", "clink": "カチン", "close": "しめる", "closes": "しめる", "closing": "しめる", "cluck": "コッコッ",
    "collision": "しょうとつ ぶつかる", "confetti": "紙ふぶき かみふぶき", "confirm": "決定 けってい OK", "confirmation": "決定 けってい OK",
    "cough": "せき", "countdown": "カウントダウン", "crack": "ひび われる", "crackle": "パチパチ", "crackling": "パチパチ", "crash": "ガシャーン",
    "creak": "ギシギシ", "creaking": "ギシギシ", "croaking": "ケロケロ", "crumpling": "くしゃくしゃ", "crunch": "ザクッ", "crying": "泣く なく",
    "cue": "合図 あいず", "death": "やられる", "defeat": "やられる 負け まけ", "delete": "消す けす", "ding": "チーン", "dismiss": "とじる",
    "draw": "ぬく", "drip": "ポタポタ しずく", "drips": "ポタポタ しずく", "dripping": "ポタポタ しずく", "drop": "落ちる おちる",
    "dropped": "落ちる おちる", "dropping": "落ちる おちる", "end": "終わり おわり", "equip": "装備 そうび", "error": "エラー まちがい",
    "exhale": "息 いき", "explosion": "爆発 ばくはつ", "fail": "失敗 しっぱい", "failure": "失敗 しっぱい", "fanfare": "ファンファーレ",
    "fart": "おなら", "firing": "発射 はっしゃ", "flap": "パタパタ", "flapping": "パタパタ はばたき", "flip": "めくる", "footstep-like": "足音 あしおと",
    "frying": "焼く やく", "gallop": "パカパカ", "galloping": "パカパカ", "gasp": "はっ おどろく", "giggle": "クスクス 笑う わらう",
    "glitch": "バグ ノイズ", "go": "スタート", "groan": "うめく", "growl": "うなる", "grunt": "うなる", "gulp": "ごくっ",
    "healing": "回復 かいふく", "hiss": "シュー", "hit": "ヒット 当たる あたる たたく", "honk": "クラクション プップー", "hooting": "ホーホー",
    "hop": "ぴょん", "hover": "カーソル", "howl": "とおぼえ", "howling": "とおぼえ", "hum": "ブーン", "impact": "衝撃 しょうげき ドン",
    "jingle": "ジングル", "jump": "ジャンプ", "jump-scare": "びっくり", "kick": "キック ける", "knock": "ノック", "knocking": "ノック",
    "landing": "着地 ちゃくち", "laugh": "笑う わらう", "laughter": "笑い声 わらいごえ", "launch": "発射 はっしゃ", "level": "レベル",
    "lift": "持ち上げる", "load": "読み込み よみこみ", "loading": "読み込み よみこみ", "lose": "負け まけ", "magic": "魔法 まほう",
    "meow": "ニャー", "meowing": "ニャー", "merge": "合体 がったい", "moo": "モー", "neigh": "ヒヒーン", "notification": "お知らせ おしらせ 通知",
    "oink": "ブーブー", "open": "あける", "opening": "あける", "pickup": "ゲット 拾う ひろう", "ping": "ピン", "pluck": "はじく",
    "pop": "ポン", "popping": "ポンポン", "pour": "そそぐ", "pouring": "そそぐ", "power-up": "パワーアップ", "power": "パワー 電源 でんげん",
    "press": "おす", "printing": "印刷 いんさつ", "projectile": "とびどうぐ", "puff": "ポフッ", "pull": "ひっぱる", "punch": "パンチ",
    "purr": "ゴロゴロ", "quack": "ガーガー", "reload": "リロード", "reset": "リセット", "rewind": "まきもどし", "ricochet": "跳弾 ちょうだん",
    "ring": "鳴る なる", "ringing": "鳴る なる", "ringtone": "着信音 ちゃくしんおん", "roar": "ほえる ガオー", "roaring": "ほえる ガオー",
    "rumble": "ゴロゴロ", "rumbling": "ゴロゴロ", "running": "走る はしる", "rustle": "カサカサ", "rustling": "カサカサ", "scrape": "こする",
    "scratch": "ひっかく", "scream": "さけび", "screech": "キーッ", "shatter": "くだける", "shattering": "くだける", "shot": "発射 はっしゃ",
    "shout": "さけぶ", "sigh": "ため息", "slam": "バタン", "slamming": "バタン", "slash": "斬る きる", "slide": "すべる", "sliding": "すべる",
    "snap": "パキッ", "sneeze": "くしゃみ", "snip": "チョキン", "snoring": "いびき", "spell": "呪文 じゅもん 魔法", "splash": "バシャ 水しぶき",
    "splat": "ベチャ", "squeak": "キュッ", "start": "スタート", "startup": "起動 きどう", "step": "足音 あしおと", "steps": "足音 あしおと",
    "stomp": "ドスン", "stop": "止まる とまる", "stops": "止まる とまる", "strike": "打つ うつ", "success": "成功 せいこう", "swing": "ふる",
    "swipe": "スワイプ", "swoosh": "シュッ", "tap": "タップ トン", "tapping": "トントン", "taps": "トントン", "tear": "やぶる", "tearing": "やぶる",
    "teleport": "テレポート ワープ", "teleportation": "テレポート ワープ", "thud": "ドスッ", "thunk": "ゴトッ", "tick": "チクタク カチッ",
    "ticking": "チクタク", "toggle": "スイッチ", "trill": "さえずり", "turn": "めくる", "typing": "タイピング", "unlock": "解除 かいじょ カギ",
    "unsheathe": "ぬく", "vanish": "消える きえる", "walk": "歩く あるく", "walking": "歩く あるく", "warp": "ワープ", "whimper": "クンクン",
    "whine": "プーン", "whip": "ムチ", "whir": "ウィーン", "whirring": "ウィーン", "whoosh": "シュッ ビュン", "whooshing": "ビュン", "win": "勝ち かち",
    "writing": "書く かく", "wrong": "まちがい ブッブー", "yawn": "あくび", "yip": "キャン", "zap": "ビリッ 電気", "zoom": "ズーム",
    # what kind
    "8-bit": "8ビット レトロ", "bit": "ビット レトロ", "retro": "レトロ", "cartoon": "アニメ まんが", "cinematic": "映画 えいが",
    "electric": "電気 でんき", "electronic": "電子 でんし", "energy": "エネルギー", "eerie": "不気味 ぶきみ こわい", "fantasy": "ファンタジー",
    "futuristic": "未来 みらい", "game": "ゲーム", "haunted": "おばけ こわい", "horror": "ホラー こわい", "medieval": "中世 ちゅうせい",
    "orchestral-style": "オーケストラ", "sci-fi": "SF 宇宙 うちゅう", "spooky": "こわい", "ui": "ボタン 画面", "underwater": "水中 すいちゅう",
    "heavy": "重い おもい", "big": "大きい おおきい", "small": "小さい ちいさい", "tiny": "小さい ちいさい", "giant": "巨大 きょだい",
    "quick": "はやい", "fast": "はやい", "slow": "ゆっくり", "soft": "やさしい", "loud": "大きい おおきい", "short": "短い みじかい",
    "long": "長い ながい", "distant": "遠く とおく", "dark": "暗い くらい", "night": "夜 よる", "morning": "朝 あさ", "evening": "夕方 ゆうがた",
    "cheerful": "明るい あかるい", "happy": "うれしい", "sad": "悲しい かなしい", "funny": "おもしろい", "comedic": "おもしろい",
    "magical": "魔法 まほう", "golden": "金 きん", "sparkling": "キラキラ", "sparkle": "キラキラ", "shimmering": "キラキラ", "glimmering": "キラキラ",
    "crystalline": "キラキラ", "bubbly": "あわ", "wet": "ぬれた", "hot": "熱い あつい", "icy": "氷 こおり", "cold": "冷たい つめたい",
    "victory": "勝利 しょうり", "triumphant": "勝利 しょうり", "epic": "すごい", "dialogue": "会話 かいわ", "text": "文字 もじ",
    "menu": "メニュー", "inventory": "持ち物 もちもの", "item": "アイテム", "upgrade": "アップグレード 強化", "trailer": "予告 よこく",
    "transition": "切り替え きりかえ", "riser": "盛り上がり", "stinger": "ジャーン", "drone": "低い音 ひくいおと", "tension": "ドキドキ",
    "dread": "こわい", "ominous": "不吉 ふきつ", "menacing": "こわい", "evil": "悪 あく", "playful": "楽しい たのしい", "joyful": "楽しい たのしい",
    "rewarding": "ごほうび", "excited": "わくわく", "amazing": "すごい", "super": "スーパー", "success-": "成功",
}

# Each category's name, and words that find it.
CATEGORIES = {
    "ui": ("UI", "ボタン・画面", "ボタン がめん クリック"),
    "retro-game": ("Retro game", "レトロゲーム", "レトロ ゲーム 8ビット ファミコン"),
    "transition": ("Transitions", "切り替え・シュッ", "きりかえ シュッ ビュン"),
    "impact": ("Impacts", "ぶつかる・たたく", "ぶつかる たたく ドン パンチ"),
    "ambience": ("Ambience", "まわりの音", "まわり かんきょう 風 雨 森"),
    "water": ("Water", "水", "みず 水 バシャ 雨"),
    "fire-electric": ("Fire and electric", "火・電気", "ひ ほのお でんき ビリビリ"),
    "footsteps": ("Footsteps", "足音", "あしおと 歩く 走る"),
    "door": ("Doors", "ドア", "ドア とびら"),
    "mechanical": ("Machines", "機械", "きかい 機械 歯車"),
    "paper-fabric": ("Paper and cloth", "紙・布", "かみ ぬの 紙 布"),
    "glass": ("Glass", "ガラス", "ガラス われる"),
    "animal": ("Animals", "動物", "どうぶつ 動物 いぬ ねこ とり"),
    "crowd": ("Crowds", "人のざわめき", "ひとびと 歓声 拍手"),
    "cartoon": ("Cartoon", "アニメ・おもしろ", "アニメ まんが おもしろい"),
    "magic-scifi": ("Magic and sci-fi", "魔法・SF", "まほう 魔法 うちゅう SF レーザー"),
    "horror": ("Horror", "ホラー", "ホラー こわい おばけ"),
    "feedback": ("Game feedback", "ゲームの合図", "あいず せいこう しっぱい レベルアップ"),
    "instrument": ("Instruments", "楽器", "がっき 楽器 ドラム ベル"),
    "office": ("Office", "事務所", "じむしょ パソコン 電話"),
    "human": ("People", "人の声", "ひと 声 こえ"),
    "vehicle": ("Vehicles", "乗り物", "のりもの 車 くるま"),
    "household": ("Home", "家の音", "いえ 家 台所"),
}
