# Hand-made characters: the ones rituals need and make, the ones that only
# come with an event, and the OG ones. (name, katakana, rarity 1-8, animal,
# thing, what it is, how you get it: "carpet", "ritual:<id>", "event:<id>",
# "admin", "fusion"). The rest of the 300 are made by make_chars.py.

SPECIALS = [
    # The characters rituals need (they come along the carpet like any other).
    ("Razzolino Coccodrillo", "ラッツォリーノ・コッコドリッロ", 4, "Coccodrillo", "Razzo", "ロケットをせおったワニ。3人で一列にならぶと空がさわがしくなる", "carpet"),
    ("La Mucca Lunare", "ラ・ムッカ・ルナーレ", 5, "Mucca", "Luna", "月をしょったウシ。3人で三角形になると いん石がふってくる", "carpet"),
    ("Treno Treno Topolino", "トレーノ・トレーノ・トポリーノ", 4, "Topo", "Treno", "でんしゃのネズミ。4人で十字にならぶと いすとりゲームが始まる", "carpet"),
    ("Matitina Ragnetta", "マティティーナ・ラニェッタ", 5, "Ragno", "Matita", "えんぴつをもったクモ。4人で四角になると ふしぎなことが起きる", "carpet"),
    ("Fungo Fungo Pinguino", "フンゴ・フンゴ・ピングイーノ", 3, "Pinguino", "Fungo", "キノコをかぶったペンギン。3人で上にかさなると かみなり！", "carpet"),
    ("Gattino Abbraccino", "ガッティーノ・アッブラッチーノ", 2, "Gatto", "Cuscino", "まくらのネコ。2人でぎゅっとくっつくと なかよしが生まれる", "carpet"),
    ("Robotto Pizzaiolo", "ロボット・ピッツァイオーロ", 6, "Robot", "Pizza", "ピザを焼くロボット。グリッチの部屋の四すみに立つと…", "carpet"),
    ("Ombrellone Squalone", "オンブレッローネ・スクアローネ", 5, "Squalo", "Ombrello", "かさをさしたサメ。カーペットのおわりを2人ずつではさむと UFO が来る", "carpet"),
    # What the rituals make.
    ("Lunavacca Stellata", "ルナヴァッカ・ステッラータ", 7, "Mucca", "Stella", "星の海からおりてきたウシ。三角形の儀式でしか会えない", "ritual:triangle"),
    ("Los Topolinos", "ロス・トポリーノス", 7, "Topo", "Treno", "いすとりゲームの勝者だけがもらえる ネズミの電車たち", "ritual:cross"),
    ("Ragnone Scolastico", "ラニョーネ・スコラスティコ", 6, "Ragno", "Libro", "本をよむ大きなクモ。四角の儀式で 99% 来る", "ritual:square"),
    ("Los Funghini", "ロス・フンギーニ", 5, "Pinguino", "Fungo", "かさなったペンギンたち。かさなりの儀式で来る", "ritual:stack"),
    ("Los Abbraccini", "ロス・アッブラッチーニ", 4, "Gatto", "Cuscino", "ぎゅっとしたネコ2ひき。なかよしの儀式で来る", "ritual:hug"),
    ("Glitchino Quattrocentoquattro", "グリッチーノ・クアットロチェントクアットロ", 7, "Robot", "Televisore", "こわれた画面からあらわれた。グリッチの儀式で来る", "ritual:corners"),
    ("Squalo Spaziale", "スクアーロ・スパツィアーレ", 7, "Squalo", "Aereo", "UFO にのってきた宇宙のサメ。はさみの儀式で来る", "ritual:sides"),
    ("Coccodrillo Bombardone", "コッコドリッロ・ボンバルドーネ", 6, "Coccodrillo", "Aereo", "空からやってくるワニ。一列の儀式のあと カーペットに来る", "ritual:line"),
    # Event characters: they walk the carpet only while their event is on.
    ("Tacone Gigante", "ターコーネ・ジガンテ", 6, "Cammello", "Taco", "タコスの日に タコスを15こ あげるともらえる", "event:taco"),
    ("Taco Taco Cammellino", "ターコ・ターコ・カンメッリーノ", 5, "Cammello", "Taco", "タコスの雨のとき カーペットに来る", "event:tacorain"),
    ("Zuccone Fantasmino", "ズッコーネ・ファンタズミーノ", 7, "Fantasma", "Zucca", "ハロウィンの夜だけ あらわれる かぼちゃのおばけ", "event:halloween"),
    ("Pipistrello Caramella", "ピピストレッロ・カラメッラ", 5, "Pipistrello", "Ciambella", "おかしの大すきなコウモリ。ハロウィンに来る", "event:halloween"),
    ("Babbo Pinguino", "バッボ・ピングイーノ", 7, "Pinguino", "Cappellone", "プレゼントをくばるペンギン。クリスマスだけ", "event:christmas"),
    ("Renna Panettone", "レンナ・パネットーネ", 5, "Renna", "Panettone", "パネットーネをのせたトナカイ。クリスマスに来る", "event:christmas"),
    ("Gatto Fortunato", "ガット・フォルトゥナート", 6, "Gatto", "Corona", "お正月の しあわせネコ。お正月だけ", "event:newyear"),
    ("Cuoricino Orsetto", "クオリチーノ・オルセット", 5, "Orso", "Palloncino", "ハートのふうせんのクマ。バレンタインに来る", "event:valentine"),
    ("Gufo Fuochino", "グーフォ・フオキーノ", 5, "Gufo", "Razzo", "花火を見るのが すきなフクロウ。夏祭りに来る", "event:summer"),
    ("Sakurino Coniglietto", "サクリーノ・コニリエット", 5, "Coniglio", "Fungo", "さくらの下で はねるウサギ。さくらふぶきの時に来る", "event:sakura"),
    ("Pesce Pescatore", "ペッシェ・ペスカトーレ", 4, "Delfino", "Ombrello", "つりが大すきなイルカ。つり大会で つれる", "event:fishing"),
    ("Balena Balenottona", "バレーナ・バレノットーナ", 6, "Balena", "Nuvola", "雲の上をおよぐクジラ。つり大会の 大物", "event:fishing"),
    ("Granchio Discoteca", "グランキオ・ディスコテーカ", 5, "Granchio", "Radio", "おどり出すカニ。カニダンスの時に来る", "event:crab"),
    ("Gatto Arcobaleno", "ガット・アルコバレーノ", 6, "Gatto", "Arcobaleno", "にじをはしるネコ。にじネコの時に来る", "event:nyan"),
    ("Tamburone Gigantone", "タンブローネ・ジガントーネ", 7, "Scimmia", "Tamburo", "大だいこをたたく巨人。たいこ襲来の時に来る", "event:drum"),
    ("Alieno Polpettino", "アリエーノ・ポルペッティーノ", 7, "Alieno", "Razzo", "UFO からおりてきた うちゅう人", "event:ufo"),
    ("DJ Delfino", "ディージェイ・デルフィーノ", 6, "Delfino", "Radio", "コンサートで音楽をかける イルカ", "event:concert"),
    ("Sole Leone", "ソーレ・レオーネ", 5, "Leone", "Sole", "たいようのたてがみのライオン。たいようフレアの時に来る", "event:solar"),
    ("Volpe Aurora", "ヴォルペ・アウローラ", 6, "Volpe", "Stella", "オーロラの夜に光るキツネ", "event:aurora"),
    ("Galassia Balenona", "ガラッシア・バレノーナ", 7, "Balena", "Luna", "銀河をおよぐクジラ。銀河の夜に来る", "event:galaxy"),
    ("Caramellino Maialino", "カラメッリーノ・マイアリーノ", 4, "Maiale", "Ciambella", "あまいものだらけのブタ。おかしの国の時に来る", "event:candy"),
    ("Panda Yin Yang", "パンダ・イン・ヤン", 6, "Panda", "Luna", "白と黒のバランスのパンダ。いんようの時に来る", "event:yinyang"),
    ("Fragolina Giraffina", "フラゴリーナ・ジラッフィーナ", 5, "Giraffa", "Fragola", "イチゴのキリン。イチゴの日に来る", "event:strawberry"),
    ("Fantasmino Lenzuolo", "ファンタズミーノ・レンツオーロ", 4, "Fantasma", "Cuscino", "シーツのおばけ。ゆうれいの夜に来る", "event:ghost"),
    ("Squalo Pinnetta", "スクアーロ・ピンネッタ", 5, "Squalo", "Scarpone", "せびれのサメ。サメのひれの時に来る", "event:shark"),
    ("Razzo Razzo Gufetto", "ラッツォ・ラッツォ・グフェット", 4, "Gufo", "Razzo", "花火にのったフクロウ。花火の時に来る", "event:fireworks"),
    ("Bollicina Medusa", "ボッリチーナ・メドゥーザ", 3, "Medusa", "Palloncino", "あわでできたクラゲ。バブルの時に来る", "event:bubbles"),
    ("Sole Pinguino Abbronzato", "ソーレ・ピングイーノ・アッブロンザート", 4, "Pinguino", "Sole", "日やけしたペンギン。夏の日に来る", "event:summer"),
    ("Fulmine Lupo", "フルミネ・ルーポ", 6, "Lupo", "Fulmine", "かみなりのオオカミ。かみなりの時に来る", "event:thunder"),
    ("Neve Orsetto Polare", "ネーヴェ・オルセット・ポラーレ", 4, "Orso", "Nuvola", "雪の日に来る しろいクマ", "event:snow"),
    ("Pioggia Ranocchietta", "ピオッジャ・ラノッキエッタ", 3, "Rana", "Ombrello", "雨の日に来る カエル", "event:rain"),
    ("Meteora Riccio", "メテオーラ・リッチョ", 5, "Riccio", "Stella", "いん石のハリネズミ。星ふりの時に来る", "event:starfall"),
    ("Lava Drago Bollente", "ラーヴァ・ドラーゴ・ボッレンテ", 6, "Drago", "Vulcano", "ようがんのドラゴン。ようがんの時に来る", "event:lava"),
    ("Cristallo Unicornone", "クリスタッロ・ウニコルノーネ", 7, "Unicorno", "Stella", "クリスタルのあらしの時だけ来る ユニコーン", "event:crystal"),
    # OG: the rarest, from the admin's lucky blocks and the biggest events.
    ("Cristallo Drago Eterno", "クリスタッロ・ドラーゴ・エテルノ", 8, "Drago", "Corona", "クリスタルでできた ドラゴンの王", "admin"),
    ("Miliardino Tostapane", "ミリアルディーノ・トスタパーネ", 8, "Robot", "Tostapane", "10おく記念に生まれた トースター", "event:billion"),
    ("Re Pizzone Supremo", "レ・ピッツォーネ・スプレーモ", 8, "Leone", "Pizza", "ピザの王さまライオン", "admin"),
    ("La Regina Gelatina", "ラ・レジーナ・ジェラティーナ", 8, "Unicorno", "Gelato", "アイスの女王", "admin"),
    ("Bimbalone Imperiale", "ビンバローネ・インペリアーレ", 8, "Elefante", "Corona", "おうかんのゾウの皇帝", "admin"),
    ("Galattico Gattissimo", "ガラッティコ・ガッティッシモ", 8, "Gatto", "Luna", "銀河いちばんのネコ", "admin"),
    ("Arcobalenone Supremo", "アルコバレノーネ・スプレーモ", 8, "Unicorno", "Arcobaleno", "にじの橋をわたる ユニコーン", "admin"),
    ("Il Grande Tamburone", "イル・グランデ・タンブローネ", 8, "Orso", "Tamburo", "世界のリズムを まもる クマ", "admin"),
    ("Polpo Dorato Eterno", "ポルポ・ドラート・エテルノ", 8, "Polpo", "Corona", "金色にかがやく タコの王", "admin"),
    ("Fantasmone Reale", "ファンタズモーネ・レアーレ", 8, "Fantasma", "Corona", "おばけの王さま", "admin"),
]
